# Generated by Django 5.2.11 on 2026-02-04 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpoch', '0016_rename_last_win_picks_tournamentbracket_last_loser_picks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupseed',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_seeding', to='corpoch.tournamentplayer', verbose_name='Group Seed'),
        ),
        migrations.AlterField(
            model_name='matchban',
            name='chart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bans', to='corpoch.chart', verbose_name='Chart Banned'),
        ),
        migrations.AlterField(
            model_name='matchban',
            name='ongoing_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_bans', to='corpoch.tournamentmatchongoing', verbose_name='Ongoing Match ID'),
        ),
        migrations.AlterField(
            model_name='matchban',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_bans', to='corpoch.groupseed', verbose_name='Player'),
        ),
        migrations.AlterField(
            model_name='tournamentround',
            name='chart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rounds_played', to='corpoch.chart', verbose_name='Chart Played'),
        ),
        migrations.AlterField(
            model_name='tournamentround',
            name='loser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rounds_lost', to='corpoch.tournamentplayer', verbose_name='Loser'),
        ),
        migrations.AlterField(
            model_name='tournamentround',
            name='ongoing_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ongoing_rounds', to='corpoch.tournamentmatchongoing', verbose_name='Ongoing Match ID'),
        ),
        migrations.AlterField(
            model_name='tournamentround',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rounds_won', to='corpoch.tournamentplayer', verbose_name='Winner'),
        ),
    ]
