# Generated by Django 5.2.11 on 2026-02-04 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpoch', '0017_alter_groupseed_player_alter_matchban_chart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentmatchongoing',
            name='ref',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Discord Ref ID'),
        ),
    ]
