# Generated by Django 5.2.11 on 2026-02-04 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpoch', '0018_tournamentmatchongoing_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentround',
            name='steg_data',
            field=models.JSONField(blank=True, null=True, verbose_name='Steg Data'),
        ),
    ]
