# Generated by Django 5.2.11 on 2026-02-08 02:27

import django.core.serializers.json
import encrypted_json_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corpoch', '0019_alter_tournamentround_steg_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gsheetapi',
            name='api_key',
            field=encrypted_json_fields.fields.EncryptedJSONField(blank=True, crypter=None, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
