# Generated by Django 5.2.11 on 2026-02-08 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corpoch', '0020_alter_gsheetapi_api_key'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gsheetapi',
            options={'verbose_name': 'Google Sheets API'},
        ),
    ]
