# Generated by Django 5.2.11 on 2026-02-08 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpoch', '0021_alter_gsheetapi_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='bracketgroup',
            name='discord',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='Group Role Discord ID'),
        ),
        migrations.AddField(
            model_name='qualifiersubmission',
            name='screenshot',
            field=models.ImageField(null=True, upload_to='qualifier_screens/', verbose_name='Screenshot'),
        ),
        migrations.AddField(
            model_name='tournamentqualifier',
            name='bracket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qualifier', to='corpoch.tournamentbracket', verbose_name='Bracket Qualifier'),
        ),
        migrations.AddField(
            model_name='tournamentqualifier',
            name='channel',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='Submission Channel ID'),
        ),
        migrations.AlterField(
            model_name='tournamentqualifier',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qualifier', to='corpoch.tournament', verbose_name='Tournament Qualifier'),
        ),
    ]
