# Generated by Django 5.2.11 on 2026-02-08 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpoch', '0022_bracketgroup_discord_qualifiersubmission_screenshot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualifiersubmission',
            name='screenshot',
            field=models.ImageField(null=True, upload_to='qualifiers/', verbose_name='Screenshot'),
        ),
        migrations.AlterField(
            model_name='tournamentconfig',
            name='rules',
            field=models.TextField(default='Some rules go here', max_length=1024, verbose_name='Rules'),
        ),
        migrations.AlterField(
            model_name='tournamentqualifier',
            name='bracket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qualifier', to='corpoch.tournamentbracket', verbose_name='Bracket'),
        ),
        migrations.AlterField(
            model_name='tournamentqualifier',
            name='channel',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='Submission Discord Channel ID'),
        ),
        migrations.AlterField(
            model_name='tournamentqualifier',
            name='end_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='tournamentqualifier',
            name='form_link',
            field=models.URLField(blank=True, null=True, verbose_name='Google Form Link'),
        ),
        migrations.AlterField(
            model_name='tournamentqualifier',
            name='gsheet',
            field=models.URLField(blank=True, null=True, verbose_name='Submissions Google Sheet'),
        ),
        migrations.AlterField(
            model_name='tournamentqualifier',
            name='rules',
            field=models.TextField(default='Placeholder rules', max_length=1024, verbose_name='Rules'),
        ),
        migrations.AlterField(
            model_name='tournamentqualifier',
            name='tournament',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='qualifier', to='corpoch.tournament', verbose_name='Tournament'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tournamentround',
            name='screenshot',
            field=models.ImageField(null=True, upload_to='rounds/', verbose_name='Screenshot'),
        ),
    ]
