# Generated by Django 5.2.11 on 2026-02-08 23:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpoch', '0023_alter_qualifiersubmission_screenshot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentqualifier',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='End Time'),
        ),
    ]
