# Generated by Django 5.2.11 on 2026-02-09 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corpoch', '0024_alter_tournamentqualifier_end_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournamentqualifier',
            old_name='qualifier_chart',
            new_name='chart',
        ),
    ]
